[geometry]

# The base area of the cistern in mÂ²
base_area = 3.80

[sensor]

# The distance in m returned by the sensor in case no object has been detected
no_detection_distance = 5.0

[detection]

# The serial port to which the sonar sensor is connected.
port = "/dev/serial0"

# The number of seconds between two successive distance detections.
interval = 900

[detection.range]

# The range detected when the cistern is full. Shorter ranges will be reported
# as this value.
min = 0.6

# The range detected when the cistern is empty. Longer ranges will be reported
# as this value.
max = 1.93
